#pragma once

#include <filament_engine/math/types.h>

#include <cstdint>
#include <cstddef>

namespace filament {
class Engine;
class Material;
class MaterialInstance;
} // namespace filament

namespace fe {

// Wraps a Filament Material and its default MaterialInstance.
// Materials are created from compiled .filamat packages (generated by matc tool).
class MaterialWrapper {
public:
    MaterialWrapper() = default;

    // Create from a compiled material package
    static MaterialWrapper create(filament::Engine& engine, const void* data, size_t size);

    // Convenience setters for common PBR parameters
    void setBaseColor(const Vec4& color);
    void setMetallic(float metallic);
    void setRoughness(float roughness);
    void setReflectance(float reflectance);

    filament::Material* getMaterial() const { return m_material; }
    filament::MaterialInstance* getInstance() const { return m_instance; }

    bool isValid() const { return m_material != nullptr && m_instance != nullptr; }

private:
    filament::Material* m_material = nullptr;
    filament::MaterialInstance* m_instance = nullptr;
};

} // namespace fe
